server:
  port: 80

# log
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug

# 数据源激活
spring:
  profiles:
    active: db5, aliyun

# typeHandler扫描器
mybatis:
  type-handlers-package: com.cskaoyan.mall.typehandler
myfile:
  config:
    net-path: http://192.168.3.62:80/
