server:
  port: 80

# log
logging:
  level:
    com:
      cskaoyan:
        mall:
          mapper: debug

# 数据源激活
spring:
  profiles:
    active: db5

# typeHandler扫描器
mybatis:
  type-handlers-package: com.cskaoyan.mall.typehandler
