spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cskaoyanmall?useSSL=false&serverTimezone=GMT%2B8
    password: 123456
    username: root
    type: com.alibaba.druid.pool.DruidDataSource